# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=400)),
                ('middle_name', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('residential_address', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=400)),
                ('middle_name', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('residential_address', models.CharField(max_length=600)),
            ],
        ),
    ]
