# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('sub_name', models.CharField(max_length=400)),
                ('no_of_students', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_number', models.CharField(max_length=400)),
                ('first_name', models.CharField(max_length=400)),
                ('middle_name', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('nationality', models.CharField(max_length=400)),
                ('profession', models.CharField(max_length=400)),
                ('special_skills', models.CharField(max_length=400)),
                ('identity_number', models.CharField(max_length=400)),
                ('number_of_children', models.CharField(max_length=400)),
                ('date_of_birth', models.DateField()),
                ('identity_type', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=400)),
                ('student_id', models.CharField(max_length=400)),
                ('term_id', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('sponsor_name', models.CharField(max_length=400)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('award_type', models.CharField(max_length=400)),
                ('payment_type', models.CharField(max_length=400)),
                ('payment_method', models.CharField(max_length=400)),
                ('details', models.CharField(max_length=400)),
                ('total_amount', models.CharField(max_length=400)),
                ('amount_payed', models.CharField(max_length=400)),
                ('amount_owed', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmissionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_number', models.CharField(max_length=400)),
                ('applied_on', models.DateField()),
                ('admitted_on', models.DateField()),
                ('admitted_by', models.CharField(max_length=400)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_graduation_date', models.DateField()),
                ('actual_graduation_date', models.DateField()),
                ('placement', models.CharField(max_length=400)),
                ('status', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollmentRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=400)),
                ('level_name', models.CharField(max_length=400)),
                ('placement', models.CharField(max_length=400)),
                ('class_name', models.CharField(max_length=400)),
                ('concentration', models.CharField(max_length=400)),
                ('cleared_for_enrollment', models.DateField()),
                ('enrollment_year', models.DateField()),
                ('enroll_on', models.DateField()),
                ('enrolled_by', models.CharField(max_length=400)),
                ('balance', models.CharField(max_length=400)),
                ('remarks', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('department_id', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=400)),
                ('academic_year_id', models.DateField()),
            ],
        ),
    ]
