# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_classes_parentdetails_scores_sponsorship_studentadmissionrecord_studentenrollmentrecords_subjects_te'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('head_of_department', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='parentdetails',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Students'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Students'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Subjects'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='term_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Terms'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Students'),
        ),
        migrations.AlterField(
            model_name='studentadmissionrecord',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Students'),
        ),
        migrations.AlterField(
            model_name='studentenrollmentrecords',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Students'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Departments'),
        ),
    ]
