# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20170805_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Classe',
        ),
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='ParentDetails',
            new_name='ParentDetail',
        ),
        migrations.RenameModel(
            old_name='Scores',
            new_name='Score',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='StudentEnrollmentRecords',
            new_name='StudentEnrollmentRecord',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
        migrations.RenameModel(
            old_name='Terms',
            new_name='Term',
        ),
    ]
