# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20170805_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classe_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.Classe'),
            preserve_default=False,
        ),
    ]
