# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20170811_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
