# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20170811_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=0, max_length=400),
            preserve_default=False,
        ),
    ]
